params = {}
params['base_name'] = 'Gathered'
params['out_dir'] = ''
params['choose_files'] = True
params['eye_paths'] = ['/home/harrysha/Dropbox/pupil/data/S18_120/Run1/S18_120-pupil_data-run1.xlsx']
params['events_paths'] = ['/home/harrysha/Dropbox/pupil/data/S18_120/Run1/events.mat']
params['impossible_upper'] = 5
params['impossible_lower'] = 1.5
params['max_blink_time'] = 500
params['min_blink_time'] = 20
params['sample_rate'] = 250
params['baseline_type'] = 'no'
params['epoch_time'] = 200
params['back_time'] = 60
params['conds_to_plot'] = 'all'
params['plot_colors'] = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf']
params['plot_style'] = ['-', '-', '-', '-', '-', '-', '-', '-', '-', '-']
params['plot_error'] = False
params['plot_title'] = 'Pupil Diameter'
params['y_label'] = 'Pupil diameter (mm)'
params['plot_fname'] = 'pupil_diameter_plot'
params['gather_dir'] = '/home/harrysha/Dropbox/data/S18_120/Gathered/'
